{
 "title": "MyCorpo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New users alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(created_at),\r\n  count(id) AS \"User count\"\r\nFROM user\r\nWHERE\r\n  $__timeFilter(created_at)\r\nGROUP BY 1\r\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  },
  {
   "title": "Events / creation date",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(id) AS \"Event count\"\nFROM evenement\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  },
  {
   "title": "Events / happening date",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,0),\n  count(id) AS \"Event count\"\nFROM evenement\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval,0)"
    }
   ]
  },
  {
   "title": "Users / date",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  avg(id) AS \"User count\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct u.id) as \"User count\",\n  count(distinct e.id) as \"Event count\",\n  (SELECT count(id) FROM evenement  WHERE `date`<CURRENT_TIMESTAMP) as \"Happened events\",\n  (SELECT count(id) FROM evenement  WHERE `date`>=CURRENT_TIMESTAMP) as \"Future events\"\nFROM user u, evenement e;"
    }
   ]
  },
  {
   "title": "Event / user",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT u.username as \"User\", count(e.id) as \"Event\" FROM `evenement` e JOIN user u ON e.creator=u.id  GROUP BY creator Order By event desc"
    }
   ]
  }
 ]
}